apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: covidprojectregistry.azurecr.io/covidapp:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "jelly-postgres.postgres.database.azure.com"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "Dsvh74uMfs9wnWM"
        - name: DATABASE_NAME
          value: "postgres"
        - name: SECRET_KEY
          value: "***secret***"
        - name: ELASTICSEARCH_DSL_HOSTS
          value: "http://40.117.136.42:9200/"
        - name: DEV
          value: "0"          
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - django-app
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: django-app
