apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: covidprojectregistry.azurecr.io/covid-web-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "jelly-postgres.postgres.database.azure.com"
        - name: DATABASE_USERNAME
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "h#qldm7Vxldf&#,39h"
        - name: DATABASE_NAME
          value: "postgres"
        - name: ES_DB
          value: "<<<<<<<<<<<<<< SET HERE >>>>>>>>>>>>>>>>>""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - django-app
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: django-app
