version: '3.7'

services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  db:
    image: "postgres:11"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dsvh74uMfs9wnWM

  web:
    build: .
    command: 
      bash -c "python /code/manage.py makemigrations && python /code/manage.py migrate && python /code/manage.py fake_users 1 && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - es

