# Generated by Django 3.0.8 on 2020-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviduser',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coviduser',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coviduser',
            name='state_province',
            field=models.CharField(max_length=80),
        ),
    ]
