# Generated by Django 3.0.8 on 2020-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviduser',
            name='hasCovid',
            field=models.BooleanField(default=True),
        ),
    ]
