# Generated by Django 3.0.8 on 2021-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201218_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviduser',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coviduser',
            name='state_province',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
