# Generated by Django 3.0.8 on 2021-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210104_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviduser',
            name='covid_risk',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
