# Generated by Django 3.0.8 on 2021-01-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210111_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='covid_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
